service: garden-party-lambda

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  apiKeys:
    - ${opt:stage}-defaultKey
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:us-east-2:292146775046:table/GardenParty'
    

plugins:
  - serverless-offline

functions: 
  api: 
    handler: src/handler.update
    events: 
      - http:
          path: logs/update
          method: post
          private: true
        